CREATE TABLE CARCATEGORY
  (
    CARCATEGORY_ID INT GENERATED ALWAYS AS IDENTITY(
    START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    NAME NVARCHAR2(256) NULL,
    DESCRIPTION NVARCHAR2(512) NULL,
    DELETED INT,
    VERSION INT,
    CREATEDBY NVARCHAR2(32),
    CREATEDDTG DATE,
    UPDATEDBY NVARCHAR2(32),
    UPDATEDDTG DATE
  );
  
  
CREATE TABLE CAR
  (
    CAR_ID INT GENERATED ALWAYS AS IDENTITY(
    START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    CATEGORY_ID INT NOT NULL,
    COLOR NVARCHAR2(32) NULL,
    NAME NVARCHAR2(256) NOT NULL,
    DESCRIPTION NVARCHAR2(512) NULL,
    PLATE_NUMBER NVARCHAR2(8) UNIQUE NOT NULL,
    PRICE   DECIMAL NULL,
    DELETED INT,
    VERSION INT,
    CREATEDBY NVARCHAR2(32),
    CREATEDDTG DATE,
    UPDATEDBY NVARCHAR2(32),
    UPDATEDDTG DATE,
    CONSTRAINT FK_FOREIGN FOREIGN KEY (CATEGORY_ID) REFERENCES CARCATEGORY (CARCATEGORY_ID)
  );
  
  
CREATE TABLE TIMECATEGORY
  (
    TIMECARTEGORY_ID INT GENERATED ALWAYS AS IDENTITY(
    START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    NAME NVARCHAR2(32) NULL,
    DESCRIPTION NVARCHAR2(512) NULL,
    DELETED INT,
    VERSION INT,
    CREATEDBY NVARCHAR2(32),
    CREATEDDTG DATE,
    UPDATEDBY NVARCHAR2(32),
    UPDATEDDTG DATE
  );
  
  
CREATE TABLE SERVICE_ORDER
  (
    ORDER_ID INT GENERATED ALWAYS AS IDENTITY(
    START WITH 1 INCREMENT BY 1) PRIMARY KEY NOT NULL,
    CAR_ID          INT NOT NULL,
    TIME_CATEGORY   INT NOT NULL,
    ORDER_DURATION  INT NOT NULL,
    PLANSTART_DTG   DATE NOT NULL,
    PLANEND_DTG     DATE NOT NULL,
    ACTUALSTART_DTG DATE NOT NULL,
    ACTUALEND_DTG   DATE NOT NULL,
    CUSTOMER_NAME NVARCHAR2(512) NOT NULL,
    DESCRIPTION NVARCHAR2(512) NULL,
    STATUS  INT NOT NULL,
    DELETED INT,
    VERSION INT,
    CREATEDBY NVARCHAR2(32),
    CREATEDDTG DATE,
    UPDATEDBY NVARCHAR2(32),
    UPDATEDDTG DATE,
    CONSTRAINT FK_FOREIGNKEY FOREIGN KEY (CAR_ID) REFERENCES CAR (CAR_ID),
    CONSTRAINT FK_FOREIGNKEY1 FOREIGN KEY (TIME_CATEGORY) REFERENCES TIMECATEGORY (TIMECARTEGORY_ID)
  );
